In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-3500-10/data3500_10

In [38]:
data=pd.read_csv('/kaggle/input/data-3500-10/data3500_10')
data=data.drop(['Unnamed: 0',' Mystery',' Novel', ' Young adult literature',' Suspense',' Speculative fiction',' Science Fiction'],1)
#data = data.loc[np.random.choice(data.index, size=3500)]
print(data.shape)
data.head()
#data.to_csv('data3500_4')

(3500, 7)

,Title,Author/Publisher,Summary,Children's literature,Crime Fiction,Fantasy,Fiction
0,Shaman's Crossing,Robin Hobb,Young Nevare Burvelle (pronounced Nuh-vair) i...,0,0,1,0
1,The Fashion in Shrouds,Margery Allingham,"Campion asks his sister, fashion designer Val...",0,1,1,1
2,River of Smoke,Amitav Ghosh,The promotional text refers to the storyline ...,0,0,0,0
3,Heaven Cent,Piers Anthony,The story begins with Prince Dolph lying in h...,0,0,1,1
4,Toby Alone,TimothÃ©e de Fombelle,"A 13-year boy named Toby Lolness, who is just...",0,0,0,0

In [39]:
import nltk
#nltk.download()
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import re

import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [40]:

def cleanbasic(sentence):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, ' ', str(sentence))
    return cleantext


def cleanPunc(sentence): #function to clean the word of any punctuation or special characters
    cleaned = re.sub(r'[?|!|\'|"|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    cleaned = cleaned.strip()
    cleaned = cleaned.replace("\n"," ")
    return cleaned


def keepAlpha(sentence):
    alpha_sent = ""
    for word in sentence.split():
        alpha_word = re.sub('[^a-z A-Z]+', ' ', word)
        alpha_sent += alpha_word
        alpha_sent += " "
    alpha_sent = alpha_sent.strip()
    return alpha_sent

In [41]:
data['Summary'] = data['Summary'].str.lower()
data['Summary'] = data['Summary'].apply(cleanbasic)
data['Summary'] = data['Summary'].apply(cleanPunc)
data['Summary'] = data['Summary'].apply(keepAlpha)
data.head()

,Title,Author/Publisher,Summary,Children's literature,Crime Fiction,Fantasy,Fiction
0,Shaman's Crossing,Robin Hobb,young nevare burvelle pronounced nuh vair is t...,0,0,1,0
1,The Fashion in Shrouds,Margery Allingham,campion asks his sister fashion designer valen...,0,1,1,1
2,River of Smoke,Amitav Ghosh,the promotional text refers to the storyline w...,0,0,0,0
3,Heaven Cent,Piers Anthony,the story begins with prince dolph lying in hi...,0,0,1,1
4,Toby Alone,TimothÃ©e de Fombelle,a year boy named toby lolness who is just one...,0,0,0,0

In [42]:
stop_words = set(stopwords.words('english'))
stop_words.update(['zero','one','two','three','four','five','six','seven','eight','nine','ten','may','also','across','among','beside','however','yet','within'])
re_stop_words = re.compile(r"\b(" + "|".join(stop_words) + ")\\W", re.I)
def removeStopWords(sentence):
    global re_stop_words
    return re_stop_words.sub(" ", sentence)

data['Summary'] = data['Summary'].apply(removeStopWords)
#data=data.drop('Unnamed: 0',1)
data.head()

,Title,Author/Publisher,Summary,Children's literature,Crime Fiction,Fantasy,Fiction
0,Shaman's Crossing,Robin Hobb,young nevare burvelle pronounced nuh vair se...,0,0,1,0
1,The Fashion in Shrouds,Margery Allingham,campion asks sister fashion designer valentin...,0,1,1,1
2,River of Smoke,Amitav Ghosh,promotional text refers storyline summar...,0,0,0,0
3,Heaven Cent,Piers Anthony,story begins prince dolph lying sister ivy...,0,0,1,1
4,Toby Alone,TimothÃ©e de Fombelle,year boy named toby lolness half milli...,0,0,0,0

In [43]:
stemmer = SnowballStemmer("english")
def stemming(sentence):
    stemSentence = ""
    for word in sentence.split():
        stem = stemmer.stem(word)
        stemSentence += stem
        stemSentence += " "
    stemSentence = stemSentence.strip()
    return stemSentence

data['Summary'] = data['Summary'].apply(stemming)
data.head()

,Title,Author/Publisher,Summary,Children's literature,Crime Fiction,Fantasy,Fiction
0,Shaman's Crossing,Robin Hobb,young nevar burvell pronounc nuh vair second s...,0,0,1,0
1,The Fashion in Shrouds,Margery Allingham,campion ask sister fashion design valentin fer...,0,1,1,1
2,River of Smoke,Amitav Ghosh,promot text refer storylin summar follow incid...,0,0,0,0
3,Heaven Cent,Piers Anthony,stori begin princ dolph lie sister ivi bed wat...,0,0,1,1
4,Toby Alone,TimothÃ©e de Fombelle,year boy name tobi lol half millimet tall live...,0,0,0,0

In [44]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data, random_state=42, test_size=0.20, shuffle=True)

In [45]:
train_text = train['Summary']
test_text = test['Summary']

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(strip_accents='unicode', analyzer='word', ngram_range=(1,3), norm='l2')
vectorizer.fit(train_text)
vectorizer.fit(test_text)

TfidfVectorizer(ngram_range=(1, 3), strip_accents='unicode')

In [47]:
x_train = vectorizer.transform(train_text)
y_train = train.drop(labels = ['Title','Author/Publisher','Summary'], axis=1)
y_train = y_train.apply(pd.to_numeric,errors='ignore')

x_test = vectorizer.transform(test_text)
y_test = test.drop(labels = ['Title','Author/Publisher','Summary'], axis=1)
y_test = y_test.apply(pd.to_numeric,errors='ignore')

In [48]:
# http://scikit.ml/api/api/skmultilearn.adapt.html#skmultilearn.adapt.MLkNN

from skmultilearn.adapt import MLkNN
from scipy.sparse import csr_matrix, lil_matrix
from sklearn.metrics import accuracy_score

In [49]:
%%time

classifier_new = MLkNN(k=10)

# Note that this classifier can throw up errors when handling sparse matrices.

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 34.8 µs

In [50]:

x_train = lil_matrix(x_train).toarray()
y_train = lil_matrix(y_train).toarray()
x_test = lil_matrix(x_test).toarray()

In [51]:
# train
classifier_new.fit(x_train, y_train)

MLkNN()

In [ ]:
# predict
predictions_new = classifier_new.predict(x_test)

In [34]:
# accuracy
print("Accuracy = ",accuracy_score(y_test,predictions_new))
print("\n")

Accuracy =  0.30142857142857143